# This example workflow will build container image
# of the application using source to image build
# startegy and push the image to ghcr.io (Image registry)

name: S2I build and push
on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  workflow_dispatch:
  push:
    # Edit to the branch(es) you want to build and deploy on each push.
    branches: [ "main" ]

#env:
#  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
#  REGISTRY_USER: ${{ github.actor }}
#  REGISTRY_PASSWORD: ${{ github.token }}
#  APP_NAME: hugo-workshop
#  IMAGE_TAGS: latest ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and push to ghcr.io
    steps:
      # Checkout spring hugo-workshop repository
      - name: Checkout
        uses: actions/checkout@v2

      # Setup S2I and build container image
      - name: Setup and Build
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
          image: ${{ env.APP_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          builder_image: 'centos/nginx-114-centos7'

      # Push image to the GitHub container registry
      - name: Push To GitHub container registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}